# Generated by Django 3.1.3 on 2021-01-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checknews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authcommittee',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
