# Generated by Django 3.1.3 on 2021-01-25 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checknews', '0002_auto_20210125_0626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authcommittee',
            old_name='c_name',
            new_name='cname',
        ),
    ]
