# Generated by Django 3.1.3 on 2021-01-25 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checknews', '0004_books'),
    ]

    operations = [
        migrations.DeleteModel(
            name='books',
        ),
        migrations.RenameField(
            model_name='authcommittee',
            old_name='cname',
            new_name='c_name',
        ),
    ]
