# Generated by Django 3.1.3 on 2021-01-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checknews', '0005_auto_20210125_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authcommittee',
            name='c_created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
