# Generated by Django 3.1.3 on 2021-01-25 06:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checknews', '0006_auto_20210125_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authcommittee',
            name='c_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
