# Generated by Django 3.1.3 on 2021-01-25 06:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checknews', '0007_auto_20210125_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='authcommittee',
            name='add_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期'),
        ),
        migrations.AlterField(
            model_name='authcommittee',
            name='c_created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
