# Generated by Django 3.1.3 on 2021-01-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checknews', '0008_auto_20210125_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authcommittee',
            name='add_date',
        ),
        migrations.AlterField(
            model_name='authcommittee',
            name='c_address',
            field=models.CharField(max_length=255, verbose_name='註冊服務處'),
        ),
        migrations.AlterField(
            model_name='authcommittee',
            name='c_author',
            field=models.CharField(max_length=255, verbose_name='註冊身份'),
        ),
        migrations.AlterField(
            model_name='authcommittee',
            name='c_cellphone',
            field=models.CharField(max_length=255, verbose_name='註冊電話'),
        ),
        migrations.AlterField(
            model_name='authcommittee',
            name='c_mail',
            field=models.CharField(max_length=255, verbose_name='註冊信箱'),
        ),
        migrations.AlterField(
            model_name='authcommittee',
            name='c_name',
            field=models.CharField(max_length=255, verbose_name='註冊姓名'),
        ),
    ]
