# Generated by Django 3.1.3 on 2021-01-25 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checknews', '0009_auto_20210125_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authcommittee',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='authAssistant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=255, verbose_name='註冊姓名')),
                ('a_mail', models.CharField(max_length=255, verbose_name='註冊信箱')),
                ('a_cellphone', models.CharField(max_length=255, verbose_name='註冊電話')),
                ('a_author', models.CharField(max_length=255, verbose_name='隸屬身份')),
                ('a_address_phone', models.CharField(max_length=255, verbose_name='註冊電話')),
                ('a_address', models.CharField(max_length=255, verbose_name='註冊服務處')),
                ('a_created_at', models.DateTimeField(auto_now=True)),
                ('committeeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checknews.authcommittee')),
            ],
            options={
                'unique_together': {('committeeId', 'a_name')},
            },
        ),
    ]
