# Generated by Django 3.1.3 on 2021-01-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checknews', '0010_auto_20210125_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authcommittee',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
