# Generated by Django 3.1.3 on 2021-01-25 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checknews', '0011_auto_20210125_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authassistant',
            name='a_address',
        ),
        migrations.RemoveField(
            model_name='authassistant',
            name='a_address_phone',
        ),
        migrations.RemoveField(
            model_name='authassistant',
            name='a_author',
        ),
        migrations.AddField(
            model_name='authcommittee',
            name='c_authId',
            field=models.CharField(default='SOME STRING', max_length=255, verbose_name='註冊身分證'),
        ),
        migrations.AlterField(
            model_name='authassistant',
            name='committeeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='隸屬身份', to='checknews.authcommittee'),
        ),
    ]
