# Generated by Django 3.1.3 on 2021-01-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checknews', '0012_auto_20210125_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authcommittee',
            name='c_authId',
            field=models.CharField(default='', max_length=255, verbose_name='註冊身分證'),
        ),
    ]
